user www-data;
worker_processes  auto;
worker_rlimit_nofile 65536;
#Подключение модуля brotli
load_module modules/ngx_http_brotli_filter_module.so;
load_module modules/ngx_http_brotli_static_module.so;


error_log  /var/log/angie/error.log notice;
pid        /run/angie.pid;


events {
    worker_connections  65536;
}


http {
    include       /etc/angie/mime.types;
    default_type  application/octet-stream;
#Из конфига нджинкс
    proxy_cache_valid 1m;
    proxy_cache_key $scheme$host$request_uri;
#Меняется путь /var/www/cache на стандартный для /var/cache/angie 
   proxy_cache_path /var/cache/angie levels=1:2 keys_zone=one:10m inactive=48h max_size=800m;
    

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    log_format extended '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" rt="$request_time" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        'h="$host" sn="$server_name" ru="$request_uri" u="$uri" '
                        'ucs="$upstream_cache_status" ua="$upstream_addr" us="$upstream_status" '
                        'uct="$upstream_connect_time" urt="$upstream_response_time"';

    access_log  /var/log/angie/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

   #Добавлено из конфига нджинкс
     gzip on;

	gzip_vary on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_buffers 16 8k;
	gzip_http_version 1.1;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
#Вставка из нджинкс
        brotli_static		on;
        brotli				on;
        brotli_comp_level	5;
        brotli_types text/plain text/css text/xml application/javascript application/json image/x-icon image/svg+xml;

    include /etc/angie/http.d/*.conf;
   #Вставка из нджинкс
    include /etc/angie/sites-enabled/*;
    
   #Вставка из нджинкс
     map $http_accept $webp_suffix {
        "~*webp"  ".webp";
    }

    map $http_accept $avif_suffix {
        "~*avif"  ".avif";
        "~*webp"  ".webp";
    }

    map $msie $cache_control {
      default "max-age=31536000, public, no-transform, immutable";
        "1"     "max-age=31536000, private, no-transform, immutable";
    }

    map $msie $vary_header {
	default "Accept";
	"1"     "";
    }
}

#stream {
#    include /etc/angie/stream.d/*.conf;
#}
